channels:
  - defaults
  - conda-forge
dependencies:
  - conda=4.7.12
  - python=3.7.4
  - h5py=2.9.0
  - numpy=1.17.2
  - pip=19.2.3
  - scipy=1.3.1
  - yaml=0.1.7
  - pyqtgraph=0.10.0
  - pillow=6.2.0
  - pip:
    - vtk==8.1.2
    - mayavi
    - PyQt5
